### ISSUE TITLE
实在是太给力了，支持！！

### ISSUE THREAD

**Issue by nezhastudio** [ethan-zf/cesium-plot-js#1]
支持！！！！

**Comment by ethan-zf** [comment]
感谢认可 :smile:

**Comment by ethan-zf** [comment]
> 支持！！！！

感谢认可 :smile:

**Comment by nezhastudio** [comment]
在使用的时候遇到了几个问题，如下：
1. 在调用remove方法后，多边形和三角形的边线并未清除。
2. 在一次创建多个绘图对象，再去绘制图形，会同时绘制好多次的绘图结果，能否提供一个方法去销毁上一次创建的绘图对象呢？

我npm install下来之后我看代码是umd的，能否修改一下上述问题呢？万分感谢！

**Comment by ethan-zf** [comment]
> 在使用的时候遇到了几个问题，如下：
> 
> 1. 在调用remove方法后，多边形和三角形的边线并未清除。
> 2. 在一次创建多个绘图对象，再去绘制图形，会同时绘制好多次的绘图结果，能否提供一个方法去销毁上一次创建的绘图对象呢？
> 
> 我npm install下来之后我看代码是umd的，能否修改一下上述问题呢？万分感谢！

第一个问题，在0.0.4版本中做了修复。
第二个问题，这个插件在设计之初就是比较开放的，各个图形间是独立的类，绘制状态相互之间无法感知到，因此建议在应用时自行维护状态来处理此问题
最后在发布的包中，提供了es module类型包

**Comment by nezhastudio** [comment]
已解决，感谢！

**Comment by nezhastudio** [comment]
我在用1.115版本开发的时候，发现一个问题。就是每次绘制后，都会自动定位到该图形，但是有时候，定位的比例尺又不准，忽大忽小。

**Comment by ethan-zf** [comment]
> 我在用1.115版本开发的时候，发现一个问题。就是每次绘制后，都会自动定位到该图形，但是有时候，定位的比例尺又不准，忽大忽小。

问题已收到，将在下个版本修复

**Comment by ethan-zf** [comment]
> 我在用1.115版本开发的时候，发现一个问题。就是每次绘制后，都会自动定位到该图形，但是有时候，定位的比例尺又不准，忽大忽小。

该问题已在0.0.5版本修复
