### ISSUE TITLE
为什么新建的图形 使用生长函数 先要让创建的元素先失去焦点才可以

### ISSUE THREAD

**Issue by wujiawei0655** [ethan-zf/cesium-plot-js#18]

**Comment by ethan-zf** [comment]
刚绘制完图形，默认进入编辑状态，编辑状态是无法触发生长动画的

**Comment by wujiawei0655** [comment]
那怎么样 绘制完退出编辑状态呢？ 谢谢！

**Comment by ethan-zf** [comment]
> 那怎么样 绘制完退出编辑状态呢？ 谢谢！

现在这种交互是默认的，好多地图绘制控件都是这样的，绘制完可以编辑，点击空白处结束绘制。如果想直接退出编辑状态可以fork下仓库，在base文件中的finishDrawing方法修改下
