### ISSUE TITLE
左键单击结束绘制的图形，如果左键双击结束会导致地图无法拖动

### ISSUE THREAD

**Issue by yanxj0** [ethan-zf/cesium-plot-js#2]
新进入页面后，激活单击结束绘制的图形，结束时使用双击，此时地图就无法拖动了

**Comment by yanxj0** [comment]
调试后发现是因为双击控制点时，LEFT_DOWN, LEFT_UP处理函数设置scene.screenSpaceCameraController.enableRotate值出了问题

**Comment by ethan-zf** [comment]
> 新进入页面后，激活单击结束绘制的图形，结束时使用双击，此时地图就无法拖动了

好的，我已复现该问题。是双击控制点的逻辑问题

**Comment by ethan-zf** [comment]
已在0.0.6版本修复
