### ISSUE TITLE
CesiumPlot.Polygon绘制还未结束时，执行remove()，polyogn清掉了，polyline还在

### ISSUE THREAD

**Issue by lovawangqi** [ethan-zf/cesium-plot-js#4]
使用本插件在做一个绘制功能，当polygon绘制到一半时想取消绘制，执行geometry.remove()，面被清掉了，线还留在地图上。
绘制FineArrow时，则功能正常
![微信截图_20240511105446](https://github.com/ethan-zf/cesium-plot-js/assets/30922946/df9c1a36-9344-40c4-a0d9-7f1c176adae9)

**Comment by lovawangqi** [comment]
使用js为：<script src="https://unpkg.com/cesium-plot-js"></script>
使用cesium：'1.104'

**Comment by ethan-zf** [comment]
该问题已在0.0.6版本修复
