### ISSUE TITLE
回显问题

### ISSUE THREAD

**Issue by yixiqingshan** [ethan-zf/cesium-plot-js#5]
可以根据绘制完成后的关键点位，绘制对应标绘吗，就是说保存到服务器后，前端再次访问时回显效果

**Comment by ethan-zf** [comment]
> 可以根据绘制完成后的关键点位，绘制对应标绘吗，就是说保存到服务器后，前端再次访问时回显效果

可以的呢，这个功能正在规划中

**Comment by ethan-zf** [comment]
该功能已在0.0.6版本实现
