### ISSUE TITLE
回显Polygon报错

### ISSUE THREAD

**Issue by Code-World-9** [ethan-zf/cesium-plot-js#7]
![base](https://github.com/ethan-zf/cesium-plot-js/assets/30791123/abfa4603-bc7e-484c-a6d0-e6cdc9656dd7)
![Polygon](https://github.com/ethan-zf/cesium-plot-js/assets/30791123/888759a6-a0b2-449a-acac-3a3a845dc53b)

**Comment by ethan-zf** [comment]
该问题已修复  #15
